### ISSUE TITLE
Jruby fails on one of the ruby decryption tests

### ISSUE THREAD

**Issue by llimllib** [department-of-veterans-affairs/connect_vbms#11]
https://travis-ci.org/department-of-veterans-affairs/connect_vbms/jobs/76146034#L269

```
1) Ruby Encrypt/Decrypt test vs Java reference impl encrypts in java, and decrypts using ruby
   Failure/Error: decrypted_xml = VBMS.decrypt_message_xml_ruby(encrypted_xml, test_pc12_server_key,
   RuntimeError:
     org.w3c.dom.DOMException: NOT_SUPPORTED_ERR: The implementation does not support the requested type of object or operation. 
   # nokogiri/XmlNode.java:1662:in `add_child_node'
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:814:in `add_child_node_and_reparent_attrs'
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:125:in `add_child'
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:405:in `parent='
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/document_fragment.rb:25:in `block in initialize'
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node_set.rb:187:in `block in each'
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node_set.rb:186:in `each'
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/document_fragment.rb:25:in `initialize'
   # nokogiri/XmlDocumentFragment.java:107:in `new'
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:355:in `fragment'
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:796:in `coerce'
   # ./vendor/bundle/jruby/2.2.0/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:257:in `replace'
   # ./vendor/bundle/jruby/2.2.0/gems/xmlenc-0.2.0/lib/xmlenc/encrypted_data.rb:39:in `decrypt'
   # ./vendor/bundle/jruby/2.2.0/gems/xmlenc-0.2.0/lib/xmlenc/encrypted_document.rb:21:in `block in decrypt'
   # ./vendor/bundle/jruby/2.2.0/gems/xmlenc-0.2.0/lib/xmlenc/encrypted_document.rb:18:in `decrypt'
   # ./src/vbms/common.rb:78:in `decrypt_message_xml_ruby'
   # ./spec/ruby_crypto_spec.rb:35:in `block in (root)'
```
