### ISSUE TITLE
Make use of quotations consistent

### ISSUE THREAD

**Issue by amoose** [department-of-veterans-affairs/connect_vbms#53]
Enable single_quotes rubocop rule. This is purely an aesthetic change for consistency. 

  - Change .rubocop.yml to include the single quotes cop (currently disabled) and auto-correct the codebase for consistency with `rubocop -a`
```
Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes
```
